#! /usr/bin/env python

from sv_utils.run import *
import argparse

parser = argparse.ArgumentParser(prog = "sv_utils")

parser.add_argument("--version", action = "version", version = "sv_utils-0.3.0")

subparsers = parser.add_subparsers()

##########
# count_summary 
count = subparsers.add_parser("count",
                              help = "summarize the frequency of each variant type (deletion, tandem_duplication, inversion, translocation) for each sample")

count.add_argument("result_list", metavar = "result_list.txt", default = None, type = str,
                    help = "1st column: sample IDs, 2nd column: tumor type, 3rd column: genomon SV result path")

count.add_argument("output", metavar = "output.txt", default = None, type = str,
                    help = "the path to the output file")

count.add_argument("--inseq", default = False, action = "store_true",
                   help = "separete variant by existence of inserted sequences")

count.set_defaults(func = count_main)

##########
# gene_summary_summary 
gene_summary = subparsers.add_parser("gene_summary",
                                     help = "summarize the frequency of each variant type (deletion, tandem_duplication, inversion, translocation) for each sample")

gene_summary.add_argument("result_list", metavar = "result_list.txt", default = None, type = str,
                          help = "1st column: sample IDs, 2nd column: tumor type, 3rd column: genomon SV result path")

gene_summary.add_argument("output", metavar = "output.txt", default = None, type = str,
                          help = "the path to the output file")

gene_summary.add_argument("annotation_dir", metavar = "annotation_dir", default = None, type = str,
                          help = "the path to the database directory")

gene_summary.add_argument("cancer_gene_list", metavar = "cancer_gene_list", default = None, type = str,
                         help = "the path to the cancer list file")

gene_summary.add_argument("--inframe_info", default = False, action = "store_true",
                         help = "add inframe information")

gene_summary.set_defaults(func = gene_summary_main)


##########
# filter
filter_parser = subparsers.add_parser("filter",
                                    help = "filter out variants outside specified conditions")

filter_parser.add_argument("result_file", metavar = "genomonSV.result.txt", default = None, type = str,
                    help = "the path to genomon SV result")

filter_parser.add_argument("output", metavar = "output.txt", default = None, type = str,
                    help = "the path to the output file")

filter_parser.add_argument("annotation_dir", metavar = "annotation_dir", default = None, type = str,
                           help = "the path to the database directory")

filter_parser.add_argument("--fisher_thres", default = 1.0, type = float,
                   help = "remove if the - log(fisher p-value) is smaller than this value")

filter_parser.add_argument("--tumor_freq_thres", default = 0.07, type = float,
                   help = "remove if the tumor allele frequency is small than this value")

filter_parser.add_argument("--normal_freq_thres", default = 0.05, type = int,
                   help = "remove if the normal allele frequency is larger than this value")

filter_parser.add_argument("--normal_depth_thres", default = 10, type = float,
                   help = "remove if the normal read depth is smaller than this value")

filter_parser.add_argument("--inversion_size_thres", default = 500, type = int,
                   help = "remove if the size of inversion is smaller than this value")

filter_parser.add_argument("--max_size_thres", default = None, type = int,
                   help = "remove if the size of variant is larger than this value")

filter_parser.add_argument("--no_control", default = False, action = "store_true",
                   help = "for the result without matched control")

filter_parser.add_argument("--within_exon", default = False, action = "store_true",
                    help = "keep only variants within exon")

filter_parser.add_argument("--control", default = None, type = str,
                    help = "the path to control data created by merge_control")

filter_parser.add_argument("--control_num_thres", default = 3, type = int,
                    help = "remove if more than specified number of control sample are found")

filter_parser.add_argument("--remove_simple_repeat", default = False, action = "store_true",
                    help = "remove variants with overlapping simple repeat annotation by UCSC")

filter_parser.add_argument("--closest_exon", default = False, action = "store_true",
                           help = "add the closest exon and distance to them")

filter_parser.add_argument("--closest_coding", default = False, action = "store_true",
                           help = "add the closest coding exon and distance to them")

filter_parser.add_argument("--mutation_result", metavar = "genomon_mutation.result.txt", default = "", type = str,
                           help = "the path to the genomon mutation result file")

filter_parser.add_argument("--reference", metavar = "reference.fa", default = "", type = str,
                           help = "the path to the reference genome sequence")

filter_parser.add_argument("--re_annotation", default = False, action = "store_true",
                           help = "gene annotaiton again")

filter_parser.add_argument("--coding_info", default = False, action = "store_true",
                           help = "get coding information")

filter_parser.add_argument("--fusion_info", metavar = "fusion_info.txt", default = None, type = str,
                           help = "the path to the fusion gene info file (gene1, gene2 and information for the 1st, 2nd and 3rd columns, respectively)")

filter_parser.set_defaults(func = filter_main)
##########

# concentrate
concentrate_parser = subparsers.add_parser("concentrate",
                                           help = "list up concentrated variants")

concentrate_parser.add_argument("result_list", metavar = "result_list.txt", default = None, type = str,
                                help = "1st column: sample IDs, 2nd column: tumor type, 3rd column: genomon SV result path")

concentrate_parser.add_argument("output", metavar = "output.txt", default = None, type = str,
                                help = "the path to the output file")

concentrate_parser.add_argument("--set_count", metavar = "set_count", default = 2, type = int,
                                help = "extract #variants is equal or more than this value within specified margin")
 
concentrate_parser.add_argument("--set_margin", metavar = "set_margin", default = 500, type = int,
                                help = "extract #variants is equal or more than the specified threshould within this value")

concentrate_parser.set_defaults(func = concentrate_main)


##########

# merge control
merge_control = subparsers.add_parser("merge_control",
                                      help = "merge, compress and index the SV list")

merge_control.add_argument("result_list", metavar = "result_list.txt", default = None, type = str,
                           help = "1st column: sample IDs, 2nd column: tumor type, 3rd column: genomon SV result path")

merge_control.add_argument("output_prefix", default = None, type = str,
                           help = "the prefix of the output file")

merge_control.set_defaults(func = merge_control_main)

##########
# realign
realign_parser = subparsers.add_parser("realign", help = "realign sv candidate to input bam file for mainly validation purpose")

realign_parser.add_argument("result_file", metavar = "genomonSV.result.txt", default = None, type = str,
                            help = "the path to genomon SV result")
    
realign_parser.add_argument("output", metavar = "output.txt", default = None, type = str,
                            help = "the path to the output file")

realign_parser.add_argument("--reference", metavar = "reference.fa", default = None, type = str, required=True,
                            help = "the path to the reference genomoe sequence")

realign_parser.add_argument("--tumor_bam", metavar = "tumor.bam", default = None, type = str, required=True,
                            help = "the path to the tumor bam file")

realign_parser.add_argument("--control_bam", metavar = "control.bam", default = None, type = str,
                            help = "the path to the control bam file (optional)")  
       
realign_parser.set_defaults(func = realign_main)

###########
# primer 
primer_parser = subparsers.add_parser("primer", help = "generate primer sequence for mainly PCR validation")

primer_parser.add_argument("result_file", metavar = "genomonSV.result.txt", default = None, type = str,
                            help = "the path to genomon SV result")

primer_parser.add_argument("output", metavar = "output.txt", default = None, type = str,
                            help = "the path to the output file")

primer_parser.add_argument("--reference", metavar = "reference.fa", default = None, type = str, required=True,
                            help = "the path to the reference genomoe sequence")

# contig_parser.add_argument("--length", default = 250, type = int,
#                            help = "size of each two sequence length from breakpoints")

primer_parser.set_defaults(func = primer_main)


##########
# convert to vcf format
format_parser = subparsers.add_parser("format", help = "convert to vcf format")

format_parser.add_argument("result_file", metavar = "genomonSV.result.txt", default = None, type = str,
                        help = "the path to genomon SV result")

format_parser.add_argument("output", metavar = "output.txt", default = None, type = str,
                        help = "the path to the output file")

format_parser.add_argument("--reference", metavar = "reference.fa", default = None, type = str, required=True,
                           help = "the path to the reference genomoe sequence")

format_parser.add_argument('--format', choices=['vcf'], default = 'vcf',
                    help = "the format of sv file. currently we only support vcfformat")

format_parser.add_argument("--max_size_thres", default = 100, type = int,
                        help = "remove if the size of variant is larger than this value")

format_parser.set_defaults(func = vcf_main)

##########

args = parser.parse_args()

args.func(args)


