#! /usr/bin/env python

from sv_utils.run import *
import argparse

parser = argparse.ArgumentParser(prog = "sv_utils")

parser.add_argument("--version", action = "version", version = "sv_utils-0.1.0")

subparsers = parser.add_subparsers()

##########
# summary 
summary_parser = subparsers.add_parser("summary",
                                    help = "summarize the frequency of each variant type (deletion, tandem_duplication, inversion, translocation) for each sample")

summary_parser.add_argument("result_list", metavar = "result_list.txt", default = None, type = str,
                    help = "1st column: sample IDs, 2nd column: genomon SV result path")

summary_parser.add_argument("output", metavar = "output.txt", default = None, type = str,
                    help = "the path to the output file")

summary_parser.add_argument("--fisher_thres", metavar = "fisher_thres", default = 1.0, type = float,
                            help = "remove if the - log(fisher p-value) is smaller than this value")

summary_parser.add_argument("--tumor_freq_thres", metavar = "tumor_freq_thres", default = 0.07, type = float,
                            help = "remove if the tumor allele frequency is small than this value")

summary_parser.add_argument("--normal_freq_thres", metavar = "normal_freq_thres", default = 0.05, type = float,
                            help = "remove if the normal allele frequency is larger than this value")

summary_parser.add_argument("--normal_depth_thres", metavar = "normal_depth_thres", default = 10, type = float,
                            help = "remove if the normal read depth is smaller than this value")

summary_parser.add_argument("--inversion_size_thres", metavar = "inversion_size_thres", default = 500, type = float,
                            help = "remove if the size of inversion is smaller than this value")

summary_parser.set_defaults(func = summary_main)

##########
args = parser.parse_args()

args.func(args)   


